# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

ArticleAsset:
  fields:
    default: article_id, photo_file_name, main, article
    form: article_id, photo_file_name, main, article
  order_by: 
  relationships: article
  filters: 
  search: 
  application: travelobd_asset

PackageAsset:
  fields:
    default: package_id, photo_file_name, main, ad
    form: package_id, photo_file_name, main, ad
  order_by: 
  relationships: ad
  filters: 
  search: 
  application: travelobd_asset

PackageVideo:
  fields:
    default: package_id, code
    form: package_id, code
  order_by: 
  relationships: 
  filters: 
  search: 
  application: travelobd_asset

SavedListing:
  fields:
    default: user_id, savable_id, user
    form: user_id, savable_id, user
  order_by: 
  relationships: user
  filters: 
  search: 
  application: travelobd_asset

SpotAsset:
  fields:
    default: spot_id, photo_file_name, main, spot
    form: spot_id, photo_file_name, main, spot
  order_by: 
  relationships: spot
  filters: 
  search: 
  application: travelobd_asset

Hotel:
  fields:
    default: name, address,  active, featured
    form: name, description, address, district, active, featured
  order_by:
  relationships: 
  filters: district
  search:
  application: travelobd

Feature:
  fields:
    default: name, for_hotel, active
    form: name, for_hotel, active
  order_by:
  relationships:
  filters: for_hotel
  search:
  application: travelobd

