# Typus Models Configuration File
#
# Use the README file as a reference to customize settings.

SavedListing:
  fields:
    default: user_id, savable_id, user
    form: user_id, savable_id, user
  order_by: 
  relationships: user
  filters: 
  search: 
  application: travelobd_asset



Hotel:
  fields:
    default: name, address,  active, featured
    form: name, description, address, district, active, featured
  order_by:
  relationships: 
  filters: district
  search:
  application: travelobd

Feature:
  fields:
    default: name, for_hotel, active
    form: name, for_hotel, active
  order_by:
  relationships:
  filters: for_hotel
  search:
  application: travelobd

Category:
  fields:
    default: title, title_bn, parent
    form: title, title_bn, parent
    options:
      selectors: parent
  order_by:
  relationships:
  search:
  application: travelobd